Repository AY2324S1-CS2103T-W17-3/tp, pull requests merged in 2023-11, with the labels that each got.

#197 Rename app in logs
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: type.Enhancement, priority.Low

#192 Refactor findPerson command
  docs/UserGuide.md
  docs/images/user-guide/addPerson.png
  docs/images/user-guide/clear.png
  docs/images/user-guide/clear1.png
  docs/images/user-guide/delete1.png
  docs/images/user-guide/deletePerson.png
  docs/images/user-guide/editPerson.png
  docs/images/user-guide/exit1.png
  docs/images/user-guide/find1.png
  docs/images/user-guide/findPerson.png
  docs/images/user-guide/list1.png
  docs/images/user-guide/listOld.png
  docs/images/user-guide/log1.png
  docs/images/user-guide/log2.png
  docs/images/user-guide/log3.png
  docs/images/user-guide/log4.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CommandAliasMap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ListPersonCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListPersonCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Task, priority.Medium

#213 Add partial description to listTransaction
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
  src/main/java/seedu/address/logic/parser/ListTransactionCommandParser.java
  src/main/java/seedu/address/model/transaction/TransactionContainsKeywordsAndPersonNamesPredicate.java
  src/main/java/seedu/address/model/transaction/TransactionContainsPersonNamesPredicate.java
  src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListTransactionCommandParserTest.java
  src/test/java/seedu/address/model/transaction/TransactionContainsPersonNamesPredicateTest.java
Labels: type.Enhancement, priority.Medium

#212 Update portions based on proportions
  src/main/java/seedu/address/logic/commands/UpdatePortionCommand.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/test/java/seedu/address/logic/commands/UpdatePortionCommandTest.java
Labels: type.Enhancement, priority.Medium

#211 Add navigable Ui with hotkeys
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/TransactionListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UiPartFocusable.java
Labels: type.Enhancement

#199 Set large window size
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Enhancement

#217 Fix Listview
  build.gradle
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PortionListView.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
Labels: type.Bug, severity.Medium

#210 Add validation for transaction commands
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/DuplicateTransactionCommand.java
  src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
  src/main/java/seedu/address/logic/commands/SettlePersonCommand.java
  src/main/java/seedu/address/logic/commands/UpdatePortionCommand.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/DuplicateTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/SettlePersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/UpdatePortionCommandTest.java
Labels: type.Bug, severity.Medium

#220 [UG] Update UG 'Navigating application using only keyboard' section
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#219 [Enhacement] Add result display focus state
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/LightTheme.css
Labels: type.Enhancement, priority.Low

#224 [UG] Add minor update to UG navigation section
  docs/UserGuide.md
Labels: type.Task, priority.Low

#227 Accept null values in config file
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/util/ConfigUtil.java
  src/test/data/ConfigUtilTest/NullPathConfig.json
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
Labels: type.Bug, severity.Medium

#228 [Task] Update User Guide URL
  src/main/java/seedu/spendnsplit/ui/HelpWindow.java
Labels: type.Task, priority.Medium

#285 Fix sorting
  src/main/java/seedu/spendnsplit/commons/util/FractionUtil.java
  src/main/java/seedu/spendnsplit/model/SpendNSplit.java
  src/test/java/seedu/spendnsplit/commons/util/FractionUtilTest.java
Labels: type.FunctionalityBug

#286 Rename address book as spendnsplit
  src/main/java/seedu/spendnsplit/logic/Logic.java
  src/main/java/seedu/spendnsplit/logic/commands/AddPersonCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/ClearCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/DeleteTransactionCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/DuplicateTransactionCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/EditPersonCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/EditTransactionCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/ExitCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/ListPersonCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/SettlePersonCommand.java
  src/main/java/seedu/spendnsplit/logic/commands/UpdatePortionCommand.java
  src/main/java/seedu/spendnsplit/model/person/Address.java
  src/main/java/seedu/spendnsplit/model/person/Email.java
  src/main/java/seedu/spendnsplit/model/person/Name.java
  src/main/java/seedu/spendnsplit/model/person/Person.java
  src/main/java/seedu/spendnsplit/model/person/Phone.java
  src/main/java/seedu/spendnsplit/model/person/TelegramHandle.java
  src/main/java/seedu/spendnsplit/model/tag/Tag.java
  src/main/java/seedu/spendnsplit/model/transaction/Amount.java
  src/main/java/seedu/spendnsplit/model/transaction/Description.java
  src/main/java/seedu/spendnsplit/model/transaction/Timestamp.java
  src/main/java/seedu/spendnsplit/model/transaction/Transaction.java
  src/test/java/seedu/spendnsplit/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/spendnsplit/logic/commands/DuplicateTransactionCommandTest.java
  src/test/java/seedu/spendnsplit/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/spendnsplit/logic/commands/EditTransactionCommandTest.java
Labels: type.Bug

#289 Fix broken UG images
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#291 Update index document
  docs/index.md
Labels: type.Task, priority.Medium

#288 Add planned enhancement for strong list input validation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jedkohjk.md
  docs/team/jeffrey-jian.md
  docs/team/wui-hong.md
Labels: type.Task, priority.Medium

#298 Add explanation on relevant transactions
  docs/UserGuide.md
Labels: type.Task, priority.Low

#308 Add clarification on command case sensitivity
  docs/UserGuide.md
Labels: priority.Medium, type.DocumentationBug

#315 Update PPP draft for v1.4
  docs/team/nathanielcalimag.md
Labels: type.Task, priority.Medium

#309 Add planned enhancement for enhanced timestamp error messages
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low

#325 Update UG with glossary
  docs/UserGuide.md
Labels: type.Task, priority.High

#321 Update acknowledgements section
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Low

#320 Add minor updates to about us
  docs/AboutUs.md
Labels: type.Task, priority.Low

#336 [UG] Update FAQ
  docs/UserGuide.md
Labels: type.Task, priority.High

#337 [DG] Update bulb label
  docs/UserGuide.md
Labels: type.Task, priority.High

#335 Update UI and Keyboard Navigation Feature section in DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/spendnsplit/ui/MainWindow.java
Labels: priority.High

#328 Add person features to the DG
  docs/DeveloperGuide.md
  docs/diagrams/AddPersonActivityDiagram.puml
  docs/diagrams/AddPersonSequenceDiagram.puml
  docs/diagrams/DeletePersonActivityDiagram.puml
  docs/diagrams/DeletePersonSequenceDiagram.puml
  docs/diagrams/DeletePersonSequenceDiagram2.puml
  docs/diagrams/EditPersonActivityDiagram.puml
  docs/diagrams/EditPersonSequenceDiagram.puml
  docs/diagrams/EditPersonSequenceDiagram2.puml
  docs/diagrams/ListPersonActivityDiagram.puml
  docs/diagrams/ListPersonSequenceDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/diagrams/SortPersonActivityDiagram.puml
  docs/diagrams/SortPersonSequenceDiagram.puml
  docs/images/AddPersonActivityDiagram.png
  docs/images/AddPersonSequenceDiagram.png
  docs/images/DeletePersonActivityDiagram.png
  docs/images/DeletePersonSequenceDiagram.png
  docs/images/DeletePersonSequenceDiagram2.png
  docs/images/EditPersonActivityDiagram.png
  docs/images/EditPersonSequenceDiagram.png
  docs/images/EditPersonSequenceDiagram2.png
  docs/images/ListPersonActivityDiagram.png
  docs/images/ListPersonSequenceDiagram.png
  docs/images/PersonClassDiagram.png
  docs/images/SortPersonActivityDiagram.png
  docs/images/SortPersonSequenceDiagram.png
  src/main/java/seedu/spendnsplit/model/person/Person.java
Labels: priority.High

#284 Add parseException for zero division in weights
  src/main/java/seedu/spendnsplit/commons/util/FractionUtil.java
  src/main/java/seedu/spendnsplit/logic/commands/SettlePersonCommand.java
  src/main/java/seedu/spendnsplit/model/transaction/Amount.java
  src/main/java/seedu/spendnsplit/model/transaction/portion/Weight.java
  src/main/java/seedu/spendnsplit/model/util/SampleDataUtil.java
  src/main/java/seedu/spendnsplit/storage/JsonAdaptedPortion.java
  src/main/java/seedu/spendnsplit/storage/JsonAdaptedTransaction.java
  src/test/java/seedu/spendnsplit/commons/util/FractionUtilTest.java
  src/test/java/seedu/spendnsplit/model/transaction/AmountTest.java
  src/test/java/seedu/spendnsplit/model/transaction/UniqueTransactionListTest.java
  src/test/java/seedu/spendnsplit/model/transaction/portion/WeightTest.java
  src/test/java/seedu/spendnsplit/storage/JsonAdaptedPortionTest.java
  src/test/java/seedu/spendnsplit/storage/JsonAdaptedTransactionTest.java
  src/test/java/seedu/spendnsplit/testutil/PortionBuilder.java
  src/test/java/seedu/spendnsplit/testutil/PortionDescriptorBuilder.java
  src/test/java/seedu/spendnsplit/testutil/TransactionBuilder.java
  src/test/java/seedu/spendnsplit/testutil/TransactionDescriptorBuilder.java
Labels: type.FunctionalityBug

#338 [UG] Finalise UG. Left with preparing PDF format
  docs/UserGuide.md
Labels: type.Task, priority.High

#319 Add efforts section to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#324 Update DG user stories
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#339 Diversify About Us roles
  docs/AboutUs.md
Labels: type.Task, priority.High

#314 Add planned enhancement for improved field validation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/spendnsplit/model/person/TelegramHandle.java
Labels: type.Task, priority.Medium

#334 Update DG model design
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.Medium

#346 Handle null values in json file
  src/main/java/seedu/spendnsplit/storage/JsonAdaptedPerson.java
  src/main/java/seedu/spendnsplit/storage/JsonSerializableSpendNSplitBook.java
  src/test/data/JsonSerializableSpendNSplitBookTest/nullValuesSpendNSplitBook.json
  src/test/java/seedu/spendnsplit/storage/JsonSerializableSpendNSplitTest.java
Labels: type.Bug

#342 Update DG storage design
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Task, priority.Medium

#347 [UG] Polish up glossary
  docs/UserGuide.md
Labels: type.Task, priority.High

#348 [UG] Prevent truncation of sample execution
  docs/UserGuide.md
Labels: type.Task, priority.High

#327 Update DG use cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#354 [UG] Additional updates
  docs/UserGuide.md
Labels: type.Task, priority.High

#344 Add planned enhancement for extending reserved names
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#358 Add planned enhancement for deleting optional Person fields
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#343 Update About Us format
  docs/AboutUs.md
Labels: type.Task, priority.Medium

#357 Add planned enhancement for better long input UI display
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#363 [UG] Create a targeted 2101 user guide
  docs/UserGuide - 2101.md
Labels: type.Task, priority.High

#367 [UG] Add page break
  docs/UserGuide2101.md
Labels: type.Task, priority.High

#369 Add minor updates to NFRs
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#372 Add minor rewording to planned enhancement
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#377 Update final PPP
  docs/team/nathanielcalimag.md
Labels: type.Task, priority.Medium

#378 Reformat final PPP
  docs/team/nathanielcalimag.md
Labels: type.Task, priority.Medium

#376 Reduce data load NFR
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low
