Repository AY2324S1-CS2103T-W17-3/tp, pull requests merged in 2023-10, with the labels that each got.

#27 Update the User Guide to include features for v1.1 and v1.2
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/user-guide/addExpense1.jpg
  docs/images/user-guide/addExpense2.jpg
  docs/images/user-guide/clear1.png
  docs/images/user-guide/createGroupExpense1.png
  docs/images/user-guide/createGroupExpense2.png
  docs/images/user-guide/delete1.png
  docs/images/user-guide/deleteExpense1.png
  docs/images/user-guide/deleteExpense2.png
  docs/images/user-guide/deleteExpense3.png
  docs/images/user-guide/editExpense1.jpg
  docs/images/user-guide/editExpense2.jpg
  docs/images/user-guide/exit1.png
  docs/images/user-guide/find1.png
  docs/images/user-guide/list1.png
  docs/images/user-guide/listOld.png
  docs/images/user-guide/log1.png
  docs/images/user-guide/log2.png
  docs/images/user-guide/log3.png
  docs/images/user-guide/log4.png
  docs/images/user-guide/settle1.jpg
  docs/images/user-guide/settle2.jpg
  docs/images/user-guide/settle3.jpg
  docs/images/user-guide/sortBalance1.png
  docs/images/user-guide/sortBalance2.png
Labels: type.Task, priority.High

#31 [DG] Add target user profile, value proposition, and user stories
  .gitignore
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#35 Add skeletal PPP for Jed
  docs/team/jedkohjk.md
Labels: type.Task, priority.High

#30 Add skeletal Jeffrey's PPP
  docs/team/jeffrey-jian.md
Labels: type.Task, priority.High

#37 Fix User Guide name
  docs/UserGuide.md
Labels: priority.Medium

#40 [PPP] Add Nathaniel's skeletal PPP
  docs/team/nathanielcalimag.md
Labels: type.Task, priority.High

#38 [PPP] Add Duy's skeletal PPP
  docs/team/ncduy0303.md
Labels: priority.High

#36 [README] Update README page
  README.md
Labels: priority.High

#39 [DG] Update NFRs and glossary
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#43 [Docs] Update website information
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/index.md
Labels: priority.High

#33 [DG] Add use cases for v1.2
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#66 [Implementation] Add Transaction model
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/test/java/seedu/address/model/transaction/AmountTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
Labels: priority.High

#65 [Implementation] Add TransactionList Model
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/transaction/TransactionList.java
  src/main/java/seedu/address/model/transaction/exceptions/TransactionNotFoundException.java
  src/test/java/seedu/address/model/transaction/TransactionListTest.java
Labels: type.Task, priority.High

#74 Change UI layout
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/spend_n_split.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Task, priority.Medium

#76 Update `Transaction` model
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
Labels: priority.High

#77 Refactor person-related commands
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#85 Rename JSON expense field
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
Labels: type.Task, priority.Medium

#86 Fix storage saving bug
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Bug, priority.High

#83 Display transactions in UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/ui/ExpenseListView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/java/seedu/address/ui/TransactionListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExpenseListView.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Task, priority.High

#89 [Task] Add sample transaction data
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/transaction/TransactionContainsPersonNamesPredicateTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/model/transaction/UniqueTransactionListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTransactionTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTransactions.java
Labels: type.Task, priority.Medium

#96 Aggregate deleted persons to others
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
  src/main/java/seedu/address/model/transaction/expense/Weight.java
  src/main/java/seedu/address/ui/ExpenseListView.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/model/transaction/expense/WeightTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Task, priority.High

#99 Fix UI datetime format
  src/main/java/seedu/address/ui/TransactionCard.java
Labels: priority.High

#95 Block adding persons with reserve names
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task, priority.High

#100 Make regex for decimals more flexible
  src/main/java/seedu/address/commons/util/FractionUtil.java
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/expense/Weight.java
  src/test/java/seedu/address/commons/util/FractionUtilTest.java
  src/test/java/seedu/address/model/transaction/AmountTest.java
  src/test/java/seedu/address/model/transaction/expense/WeightTest.java
Labels: priority.Low

#90 Add settle command
  src/main/java/seedu/address/logic/commands/SettlePersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SettlePersonCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SettlePersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/SettlePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/SettlePersonCommandParserTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Story, priority.High

#98 Sort transactions by recency
  src/main/java/seedu/address/model/transaction/Timestamp.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
Labels: type.Task, priority.Medium

#105 [Task] Add minor fixes to storage
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/expense/Weight.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/transaction/AmountTest.java
  src/test/java/seedu/address/model/transaction/expense/WeightTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTransactionTest.java
Labels: type.Bug, priority.High

#110 [Task] Add minor fixes to storage
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/expense/Weight.java
  src/test/java/seedu/address/model/transaction/AmountTest.java
  src/test/java/seedu/address/model/transaction/expense/WeightTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTransactionTest.java
Labels: type.Task, priority.High

#111 [Task] Fix name bugs
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Task, priority.High

#112 Add balance to UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/model/transaction/UniqueTransactionListTest.java
Labels: type.Task, priority.High

#93 Add support for Editing Transactions
  src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditTransactionCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditTransactionCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditTransactionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
  src/test/java/seedu/address/testutil/TransactionUtil.java
  src/test/java/seedu/address/testutil/TypicalTransactions.java
Labels: type.Story, priority.High

#114 Add sort by balance for persons
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/SettlePersonCommandIntegrationTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.Medium

#132 [Enhancement] Change theme to light mode
  src/main/java/seedu/address/ui/NameLabel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/fonts/Poppins/OFL.txt
  src/main/resources/fonts/Poppins/static/Poppins-Black.ttf
  src/main/resources/fonts/Poppins/static/Poppins-BlackItalic.ttf
  src/main/resources/fonts/Poppins/static/Poppins-Bold.ttf
  src/main/resources/fonts/Poppins/static/Poppins-BoldItalic.ttf
  src/main/resources/fonts/Poppins/static/Poppins-ExtraBold.ttf
  src/main/resources/fonts/Poppins/static/Poppins-ExtraBoldItalic.ttf
  src/main/resources/fonts/Poppins/static/Poppins-ExtraLight.ttf
  src/main/resources/fonts/Poppins/static/Poppins-ExtraLightItalic.ttf
  src/main/resources/fonts/Poppins/static/Poppins-Italic.ttf
  src/main/resources/fonts/Poppins/static/Poppins-Light.ttf
  src/main/resources/fonts/Poppins/static/Poppins-LightItalic.ttf
  src/main/resources/fonts/Poppins/static/Poppins-Medium.ttf
  src/main/resources/fonts/Poppins/static/Poppins-MediumItalic.ttf
  src/main/resources/fonts/Poppins/static/Poppins-Regular.ttf
  src/main/resources/fonts/Poppins/static/Poppins-SemiBold.ttf
  src/main/resources/fonts/Poppins/static/Poppins-SemiBoldItalic.ttf
  src/main/resources/fonts/Poppins/static/Poppins-Thin.ttf
  src/main/resources/fonts/Poppins/static/Poppins-ThinItalic.ttf
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low

#130 Change prefix to use "=" instead of "/"
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.Low, severity.Low

#137 [Enhancement] Add gap between persons and transactions list
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low

#142 Cascade edited names to transactions
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
Labels: type.Task, priority.High

#113 Add group transaction feature
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddTransactionCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/Description.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/expense/Weight.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTransactionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/transaction/DescriptionTest.java
  src/test/java/seedu/address/model/transaction/expense/WeightTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
Labels: type.Task, priority.High

#143 Show reserved name error message if editing a persons name to a reserved name
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
Labels: type.Task, priority.High

#152 [Task] Editable transaction payee
  src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
  src/main/java/seedu/address/logic/parser/EditTransactionCommandParser.java
  src/test/java/seedu/address/logic/parser/EditTransactionCommandParserTest.java
Labels: type.Task, priority.High

#147 Make the lists consistent in the +/- sign of balances
  src/main/java/seedu/address/ui/TransactionCard.java
Labels: type.Task, priority.High

#144 Add ability to edit timestamp in EditTransactionCommand
  src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditTransactionCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/EditTransactionCommandParserTest.java
Labels: type.Story, priority.High

#154 Update developer guide to rename expenses to transactions
  docs/DeveloperGuide.md
Labels: type.Task, severity.Low

#161 Enable gradle assertions
  build.gradle
Labels: type.Task, priority.High

#148 Synchronise names in lists
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
Labels: type.Task, priority.High

#145 Friendlier Expense Strings
  src/main/java/seedu/address/model/transaction/portion/Portion.java
Labels: type.Enhancement, priority.Medium

#138 [Enhancement] Update name label to be user friendly
  src/main/java/seedu/address/ui/NameLabel.java
Labels: type.Enhancement, priority.Low

#171 [DG] Add Manual Testing for deleting a transaction in DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Low

#170 EditTransaction command checks for irrelevant transactions
  src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
  src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
Labels: type.Bug, priority.High

#173 [UG] Add GUI section, update edit transaction commands
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/user-guide/editExpense1.jpg
  docs/images/user-guide/editExpense2.jpg
  docs/images/user-guide/editTransactionSuccess.png
  docs/images/user-guide/labelledUi.png
  docs/images/user-guide/updatePortionSuccess.png
Labels: type.Task

#174 [DG] Add minor updates to DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/user-guide/settle1.jpeg
  docs/images/user-guide/settle1.jpg
  docs/images/user-guide/settle2.jpeg
  docs/images/user-guide/settle2.jpg
  docs/images/user-guide/settle3.jpg
Labels: type.Task, priority.Medium

#169 Remove portion-related fields and methods
  src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
  src/main/java/seedu/address/logic/parser/EditTransactionCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/EditTransactionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TransactionUtil.java
Labels: type.Task, priority.Medium

#184 Bring back TOC
  docs/UserGuide.md
Labels: type.Task

#157 Add optional timestamp field to addTransaction
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddTransactionCommandParser.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTransactionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/transaction/UniqueTransactionListTest.java
Labels: type.Task, priority.High

#198 Account for reserved names in data file
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.High

#196 Change JavaFX version to fix ListView
  build.gradle
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PortionListView.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
Labels: type.Bug, priority.High

#155 Add command alias feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SetShorthandCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CommandAliasMap.java
  src/main/java/seedu/address/logic/parser/SetShorthandCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/SetShorthandCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandAliasMapTest.java
  src/test/java/seedu/address/logic/parser/SetShorthandCommandParserTest.java
Labels: priority.High

#190 Make non-name fields optional for persons
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium

#194 Make time format friendly
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
  src/main/java/seedu/address/model/transaction/Timestamp.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditTransactionCommandParserTest.java
  src/test/java/seedu/address/model/transaction/TimestampTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
  src/test/java/seedu/address/testutil/TypicalTransactions.java
Labels: type.Enhancement, priority.Medium

#195 Validate transactions
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateTransactionAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTransactionAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/transaction/UniqueTransactionListTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Bug, priority.High

#203 [UG] Update Introduction and FAQ
  docs/UserGuide.md
Labels: type.Task, priority.High

#200 Add optional timestamp to settlePerson
  src/main/java/seedu/address/logic/commands/SettlePersonCommand.java
  src/main/java/seedu/address/logic/parser/SettlePersonCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/transaction/Timestamp.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
  src/test/data/JsonSerializableAddressBookTest/duplicateTransactionAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTransactionAddressBook.json
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/SettlePersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/SettlePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/SettlePersonCommandParserTest.java
  src/test/java/seedu/address/model/transaction/TimestampTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
Labels: type.Task, priority.High

#208 Add duplicateTransaction to list of parsed commands in aliasmap
  src/main/java/seedu/address/logic/parser/CommandAliasMap.java
Labels: type.Bug, priority.High, severity.High
